version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka1:
    image: 'bitnami/kafka:latest'
    ports:
      - '9091:9091'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_DEFAULT_REPLICATION_FACTOR=5
      - KAFKA_LISTENERS=PLAINTEXT://:9091
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9091
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_NUM_PARTITIONS=5
      - KAFKA_REPLICATION_FACTOR=5
      - KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS=5
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=5
      - KAFKA_TRANSACTION_STATE_LOG_NUM_PARTITIONS=5
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=5
      - BOOTSTRAP_SERVERS=kafka1:9091,kafka2:9092,kafka3:9093,kafka4:9094,kafka5:9095
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  kafka2:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=5
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_NUM_PARTITIONS=5
      - KAFKA_REPLICATION_FACTOR=5
      - KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS=5
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=5
      - KAFKA_TRANSACTION_STATE_LOG_NUM_PARTITIONS=5
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=5
      - BOOTSTRAP_SERVERS=kafka1:9091,kafka2:9092,kafka3:9093,kafka4:9094,kafka5:9095
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  kafka3:
    image: 'bitnami/kafka:latest'
    ports:
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_DEFAULT_REPLICATION_FACTOR=5
      - KAFKA_LISTENERS=PLAINTEXT://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9093
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_NUM_PARTITIONS=5
      - KAFKA_REPLICATION_FACTOR=5
      - KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS=5
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=5
      - KAFKA_TRANSACTION_STATE_LOG_NUM_PARTITIONS=5
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=5
      - BOOTSTRAP_SERVERS=kafka1:9091,kafka2:9092,kafka3:9093,kafka4:9094,kafka5:9095
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  kafka4:
    image: 'bitnami/kafka:latest'
    ports:
      - '9094:9094'
    environment:
      - KAFKA_BROKER_ID=4
      - KAFKA_DEFAULT_REPLICATION_FACTOR=5
      - KAFKA_LISTENERS=PLAINTEXT://:9094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka4:9094
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_NUM_PARTITIONS=5
      - KAFKA_REPLICATION_FACTOR=5
      - KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS=5
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=5
      - KAFKA_TRANSACTION_STATE_LOG_NUM_PARTITIONS=5
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=5
      - BOOTSTRAP_SERVERS=kafka1:9091,kafka2:9092,kafka3:9093,kafka4:9094,kafka5:9095
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  kafka5:
    image: 'bitnami/kafka:latest'
    ports:
      - '9095:9095'
    environment:
      - KAFKA_BROKER_ID=5
      - KAFKA_DEFAULT_REPLICATION_FACTOR=5
      - KAFKA_LISTENERS=PLAINTEXT://:9095
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka5:9095
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_NUM_PARTITIONS=5
      - KAFKA_REPLICATION_FACTOR=5
      - KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS=5
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=5
      - KAFKA_TRANSACTION_STATE_LOG_NUM_PARTITIONS=5
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=5
      - BOOTSTRAP_SERVERS=kafka1:9091,kafka2:9092,kafka3:9093,kafka4:9094,kafka5:9095
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper