show databases;
CREATE DATABASE loja_virtual;
USE loja_virtual;
CREATE TABLE PRODUTO (id INT AUTO_INCREMENT, nome VARCHAR(50) NOT NULL, descricao VARCHAR(255), PRIMARY KEY(id)) Engine = InnoDb;
show processlist;
CREATE TABLE CATEGORIA (ID INT AUTO_INCREMENT, NOME VARCHAR(50) NOT NULL, PRIMARY KEY(ID)) Engine = InnoDB;
ALTER TABLE PRODUTO ADD COLUMN CATEGORIA_ID INT;
ALTER TABLE PRODUTO ADD FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA(ID);
SELECT C.ID, C.NOME, P.ID, P.NOME, P.DESCRICAO FROM CATEGORIA C INNER JOIN PRODUTO P ON C.ID = P.CATEGORIA_ID;
